<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
<<<<<<< HEAD
  <suite name="Default suite" duration-ms="152693" started-at="2016-01-12T08:01:48Z" finished-at="2016-01-12T08:04:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="152693" started-at="2016-01-12T08:01:48Z" finished-at="2016-01-12T08:04:21Z">
      <class name="Functional_Scenarios.DownloadFromPlayStore">
        <test-method status="PASS" signature="initializeDrivers()[pri:0, instance:Functional_Scenarios.DownloadFromPlayStore@1f57539]" name="initializeDrivers" is-config="true" duration-ms="19548" started-at="2016-01-12T13:31:48Z" finished-at="2016-01-12T13:32:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDrivers -->
        <test-method status="FAIL" signature="verifyPlayStoreAppInstallationFunctionality()[pri:0, instance:Functional_Scenarios.DownloadFromPlayStore@1f57539]" name="verifyPlayStoreAppInstallationFunctionality" duration-ms="130844" started-at="2016-01-12T13:32:08Z" finished-at="2016-01-12T13:34:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at Functional_Scenarios.DownloadFromPlayStore.verifyPlayStoreAppInstallationFunctionality(DownloadFromPlayStore.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPlayStoreAppInstallationFunctionality -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Functional_Scenarios.DownloadFromPlayStore@1f57539]" name="tearDown" is-config="true" duration-ms="2272" started-at="2016-01-12T13:34:19Z" finished-at="2016-01-12T13:34:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPlayStoreAppInstallationFunctionality status=FAILURE method=DownloadFromPlayStore.verifyPlayStoreAppInstallationFunctionality()[pri:0, instance:Functional_Scenarios.DownloadFromPlayStore@1f57539] output={null}]]]>
=======
  <suite name="Default suite" duration-ms="44000" started-at="2016-01-12T07:44:49Z" finished-at="2016-01-12T07:45:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44000" started-at="2016-01-12T07:44:49Z" finished-at="2016-01-12T07:45:33Z">
      <class name="Functional_Scenarios.MyAccountScenario">
        <test-method status="PASS" signature="initializeDrivers()[pri:0, instance:Functional_Scenarios.MyAccountScenario@27a8c74e]" name="initializeDrivers" is-config="true" duration-ms="17316" started-at="2016-01-12T13:14:49Z" finished-at="2016-01-12T13:15:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDrivers -->
        <test-method status="PASS" signature="logOutPopupOnMyAccount()[pri:0, instance:Functional_Scenarios.MyAccountScenario@27a8c74e]" name="logOutPopupOnMyAccount" duration-ms="25280" started-at="2016-01-12T13:15:06Z" finished-at="2016-01-12T13:15:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutPopupOnMyAccount -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Functional_Scenarios.MyAccountScenario@27a8c74e]" name="tearDown" is-config="true" duration-ms="1378" started-at="2016-01-12T13:15:32Z" finished-at="2016-01-12T13:15:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logOutPopupOnMyAccount status=SUCCESS method=MyAccountScenario.logOutPopupOnMyAccount()[pri:0, instance:Functional_Scenarios.MyAccountScenario@27a8c74e] output={null}]]]>
>>>>>>> 577daaf9b204ea7e18c2b2c2537b1f5c74c58ab5
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
<<<<<<< HEAD
        <test-method status="PASS" signature="quitTest()[pri:0, instance:Functional_Scenarios.DownloadFromPlayStore@1f57539]" name="quitTest" is-config="true" duration-ms="5" started-at="2016-01-12T13:34:21Z" finished-at="2016-01-12T13:34:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitTest -->
        <test-method status="FAIL" signature="afterExecution()[pri:0, instance:Functional_Scenarios.DownloadFromPlayStore@1f57539]" name="afterExecution" is-config="true" duration-ms="0" started-at="2016-01-12T13:34:21Z" finished-at="2016-01-12T13:34:21Z">
=======
        <test-method status="PASS" signature="quitTest()[pri:0, instance:Functional_Scenarios.MyAccountScenario@27a8c74e]" name="quitTest" is-config="true" duration-ms="0" started-at="2016-01-12T13:15:33Z" finished-at="2016-01-12T13:15:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitTest -->
        <test-method status="FAIL" signature="afterExecution()[pri:0, instance:Functional_Scenarios.MyAccountScenario@27a8c74e]" name="afterExecution" is-config="true" duration-ms="0" started-at="2016-01-12T13:15:33Z" finished-at="2016-01-12T13:15:33Z">
>>>>>>> 577daaf9b204ea7e18c2b2c2537b1f5c74c58ab5
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[com/sun/mail/util/MailLogger]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: com/sun/mail/util/MailLogger
	at javax.mail.Session.initLogger(Session.java:230)
	at javax.mail.Session.<init>(Session.java:214)
	at javax.mail.Session.getInstance(Session.java:251)
	at Utility.SendExecutionReport.sendMail(SendExecutionReport.java:62)
<<<<<<< HEAD
	at BugRegressionSuite.BaseTestBugRegression.afterExecution(BaseTestBugRegression.java:426)
=======
	at BugRegressionSuite.BaseTestBugRegression.afterExecution(BaseTestBugRegression.java:428)
>>>>>>> 577daaf9b204ea7e18c2b2c2537b1f5c74c58ab5
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:336)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.lang.ClassNotFoundException: com.sun.mail.util.MailLogger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterExecution -->
<<<<<<< HEAD
      </class> <!-- Functional_Scenarios.DownloadFromPlayStore -->
=======
      </class> <!-- Functional_Scenarios.MyAccountScenario -->
>>>>>>> 577daaf9b204ea7e18c2b2c2537b1f5c74c58ab5
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
